baseURL = "https://rajkumaar.co.in"
title = "Online Home of Rajkumar S"
DefaultContentLanguage = "en"
theme = "hello-friend-ng"

[author]
name = "Rajkumar S"

[params]
dateform = "Jan 2, 2006"
dateformShort = "Jan 2"
dateformNum = "2006-01-02"
dateformNumTime = "2006-01-02 15:04 -0700"
description = "Online home of Rajkumar S"
contentTypeName = "posts"
keywords = "rajkumar, homepage, portfolio, vCard, rajkumar, rajkumaar23"
homeSubtitle = "Software Engineer Intern | CodeChef"
profileImage = "https://avatars0.githubusercontent.com/u/37476886?s=460&v=4"
defaultTheme = "dark"
themeColor = "#252627"
disqusShortname = "rajkumaar23"

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true

# Colors for favicons
[params.favicon.color]
mask = "#252627"
msapplication = "#252627"
theme = "#252627"

[params.logo]
logoText = "$ cd /home"
logoHomeLink = "/"

# Social icons
[[params.social]]
name = "github"
url = "https://github.com/rajkumaar23"

[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/rajkumaar23"

[[params.social]]
name = "twitter"
url = "https://twitter.com/rajkumaar23"

[[params.social]]
name = "gpg"
url = "/pgp.txt"

[[params.social]]
name = "email"
url = "mailto:rajkumaar2304@icloud.com"

[[params.social]]
name = "telegram"
url = "https://t.me/rajkumaar23"

[menu]

[[menu.main]]
identifier = "about"
name = "about"
url = "about/"

[[menu.main]]
identifier = "resume"
name = "resume"
url = "resume.pdf"

[[menu.main]]
name = "posts"
url = "/posts"

[[menu.main]]
name = "bookshelf"
url = "/books/shelf"
